# Use the official Docker Hub Ubuntu 16.04 Image
FROM ubuntu:16.04

# Update the base image
RUN apt-get update && apt-get dist-upgrade -y && apt-get autoremove --purge -y

# Install impitool and curl
RUN apt-get install curl ipmitool git -y

# Install slacktee
RUN git clone https://github.com/course-hero/slacktee.git && cp slacktee/slacktee.sh /usr/local/bin/ && rm -rf slacktee

# Set slacktee config file
RUN slacktee_config="IyAtLS0tLS0tLS0tCiMgQ29uZmlndXJhdGlvbgojICAgRGVzY3JpYmVzIHRoZSBJbmNvbWluZyBXZWJob29rIGFsbG93aW5nIHlvdSB0byBwb3N0IG1lc3NhZ2VzIGludG8gU2xhY2suCiMgICBBZnRlciB0aGUgY29uZmlndXJhdGlvbiwgY29weSB0aGlzIGZpbGUgdG8gL2V0YyBvciB5b3VyIGhvbWUgZGlyZWN0b3J5LgojICAgTk9URSA6IFBsZWFzZSByZW5hbWUgdGhpcyBmaWxlIHRvICcuc2xhY2t0ZWUnLCBpZiB5b3UnZCBsaWtlIHRvIHBsYWNlIHRoaXMgaW4geW91ciBob21lIGRpcmVjdG9yeS4KIyAtLS0tLS0tLS0tCndlYmhvb2tfdXJsPSIiICAgICAgIyBJbmNvbWluZyBXZWJob29rcyBpbnRlZ3JhdGlvbiBVUkwuIFNlZSBodHRwczovL215LnNsYWNrLmNvbS9zZXJ2aWNlcy9uZXcvaW5jb21pbmctd2ViaG9vawp1cGxvYWRfdG9rZW49IiIgICAgICMgVGhlIHVzZXIncyBBUEkgYXV0aGVudGljYXRpb24gdG9rZW4sIG9ubHkgdXNlZCBmb3IgZmlsZSB1cGxvYWRzLiBTZWUgaHR0cHM6Ly9hcGkuc2xhY2suY29tLyNhdXRoCmNoYW5uZWw9IiIgICAgICAgICAgIyBEZWZhdWx0IGNoYW5uZWwgdG8gcG9zdCBtZXNzYWdlcy4gJyMnIGlzIHByZXBlbmRlZCwgaWYgaXQgZG9lc24ndCBzdGFydCB3aXRoICcjJyBvciAnQCcuCnRtcF9kaXI9Ii90bXAiICAgICAgIyBUZW1wb3JhcnkgZmlsZSBpcyBjcmVhdGVkIGluIHRoaXMgZGlyZWN0b3J5Lgp1c2VybmFtZT0iIiAgICAgICAgICMgRGVmYXVsdCB1c2VybmFtZSB0byBwb3N0IG1lc3NhZ2VzLgppY29uPSJnaG9zdCIgICAgICAgICMgRGVmYXVsdCBlbW9qaSBvciBhIGRpcmVjdCB1cmwgdG8gYW4gaW1hZ2UgdG8gcG9zdCBtZXNzYWdlcy4gWW91IGRvbid0IGhhdmUgdG8gd3JhcCBlbW9qaSB3aXRoICc6Jy4gU2VlIGh0dHA6Ly93d3cuZW1vamktY2hlYXQtc2hlZXQuY29tLgphdHRhY2htZW50PSIiICAgICAgICMgRGVmYXVsdCBjb2xvciBvZiB0aGUgYXR0YWNobWVudHMuIElmIGFuIGVtcHR5IHN0cmluZyBpcyBzcGVjaWZpZWQsIHRoZSBhdHRhY2htZW50cyBhcmUgbm90IHVzZWQuCg==" && echo $slacktee_config |base64 -d | tee /etc/slacktee.conf

# Copy the entrypoint script into the container
COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

# Load the entrypoint script to be run later
ENTRYPOINT ["/docker-entrypoint.sh"]
